services:
  node-red:
    build:
      context: ./NodeRed/ConfigurationFiles
    container_name: node-red
    user: "0"
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
    ports:
      - "1880:1880"
    devices:
      - /dev/gpiomem
    volumes:
      - ./NodeRed/Data:/data
    group_add:
      - dialout
